// Centralized Mock Database for Replate / FoodBridge
// Single Source of Truth for surplus foods across Explore, Dashboard Explore, and Dashboard Consumer

export interface MockFoodItem {
  id: string;
  title: string;
  description: string;
  providerName: string;
  providerPhone: string;
  providerAddress: string;
  originalPrice: number;
  discountPrice: number;
  price: number;
  quantity: string;
  pickupTime: string;
  distance: string;
  category: 'MAKANAN_BERAT' | 'ROTI_KUE' | 'MINUMAN_SUSU' | 'BUAH_SAYUR' | 'BAHAN_MENTAH';
  isFree: boolean;
  type: 'RESCUE_SALE' | 'DONATION';
  imageUrl: string;
  rating: number;
  storageCondition: 'ROOM_TEMP' | 'HOT_HOLDING' | 'CHILLED';
  packagingType: 'PACKAGED' | 'STERILE_CONTAINER' | 'BULK';
  weightPerUnitKg: number;
  allergens: string[];
  lat: number;
  lng: number;
  status: 'AVAILABLE' | 'CLAIMED' | 'EXPIRED' | 'OUT_OF_STOCK' | 'SOLD_OUT';
}

export const MOCK_SURPLUS_FOODS: MockFoodItem[] = [
  {
    id: 'FOD-001',
    title: 'Nasi Paket Ayam Bakar Madu',
    description: 'Nasi hangat dengan ayam bakar madu bumbu rempah, lalapan segar, dan sambal terasi terpisah dalam wadah higienis berstandar BPOM.',
    providerName: 'Warung Bakso Pak Kumis',
    providerPhone: '081234567891',
    providerAddress: 'Jl. Genteng Kali No. 45, Genteng, Surabaya',
    originalPrice: 28000,
    discountPrice: 12000,
    price: 12000,
    quantity: '15 Porsi',
    pickupTime: '19:30 - 21:30 WIB',
    distance: '0.8 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Wadah Steril Food Grade'],
    lat: -7.2575,
    lng: 112.7521,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-002',
    title: 'Roti Croissant & Choco Pastry Halal',
    description: 'Aneka roti croissant butter dan pastry cokelat lembut yang baru dipanggang hari ini di outlet bakery, tersegel steril.',
    providerName: 'Rotiboy Bakery Surabaya',
    providerPhone: '081234567892',
    providerAddress: 'Tunjungan Plaza Lt. G, Jl. Basuki Rahmat, Surabaya',
    originalPrice: 18000,
    discountPrice: 6000,
    price: 6000,
    quantity: '25 Porsi',
    pickupTime: '20:00 - 22:00 WIB',
    distance: '1.2 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.25,
    allergens: ['Dairy (Susu)', 'Halal BPJPH', 'Bebas Pengawet'],
    lat: -7.2614,
    lng: 112.7385,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-003',
    title: 'Prasmanan Nasi Goreng & Ayam Goreng Buffet',
    description: 'Menu buffet katering hotel bintang 5 yang tidak tersentuh tamu, disimpan di warm chafing dish dengan suhu terjaga >60°C.',
    providerName: 'Hotel Majapahit Surabaya',
    providerPhone: '081234567893',
    providerAddress: 'Jl. Tunjungan No. 65, Surabaya',
    originalPrice: 45000,
    discountPrice: 0,
    price: 0,
    quantity: '30 Porsi',
    pickupTime: '20:30 - 22:00 WIB',
    distance: '2.1 km',
    category: 'MAKANAN_BERAT',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'STERILE_CONTAINER',
    weightPerUnitKg: 0.45,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Steril Food Grade'],
    lat: -7.2637,
    lng: 112.7407,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-004',
    title: 'Sop Buntut Sapi Kuah Rempah Steril',
    description: 'Sop buntut daging sapi dengan kuah kaldu rempah kaya gizi, dikemas dalam mangkok microwaveable kedap udara.',
    providerName: 'Dapur Katering Bu Rudy',
    providerPhone: '081234567894',
    providerAddress: 'Jl. Dharmahusada No. 140, Gubeng, Surabaya',
    originalPrice: 35000,
    discountPrice: 15000,
    price: 15000,
    quantity: '12 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '1.5 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Bebas MSG Berlebih'],
    lat: -7.2689,
    lng: 112.7681,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-005',
    title: 'Paket Roti Tawar Gandum & Donat Susu',
    description: 'Paket roti gandum tinggi serat dan donat tabur gula halus, higienis untuk sarapan atau camilan anak panti asuhan.',
    providerName: 'Bakery Plaza Surabaya',
    providerPhone: '081234567895',
    providerAddress: 'Jl. Pemuda No. 33, Surabaya Pusat',
    originalPrice: 22000,
    discountPrice: 0,
    price: 0,
    quantity: '20 Porsi',
    pickupTime: '20:30 - 21:45 WIB',
    distance: '1.8 km',
    category: 'ROTI_KUE',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.3,
    allergens: ['Dairy (Susu)', 'Halal BPJPH'],
    lat: -7.2655,
    lng: 112.7472,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-006',
    title: 'Sayur Sop Ayam Kaldu Organik (Porsi Jumbo)',
    description: 'Sup sayur kaldu ayam kaya nutrisi dengan wortel, kubis, brokoli segar steril dimasak higienis.',
    providerName: 'Dapur Sehat Bunda',
    providerPhone: '081234567896',
    providerAddress: 'Jl. Raya Darmo No. 12, Wonokromo, Surabaya',
    originalPrice: 22000,
    discountPrice: 8000,
    price: 8000,
    quantity: '14 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '2.1 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Bebas Pengawet', 'Rendah Garam', 'Halal'],
    lat: -7.265,
    lng: 112.75,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-007',
    title: 'Paket Dimsum Ayam & Siomay Kukus',
    description: 'Siomay dimsum ayam segar buatan pagi hari di restoran dimsum, steril dan lengkap dengan saus sambal sachet.',
    providerName: 'Dimsum Delight Nusantara',
    providerPhone: '081234567897',
    providerAddress: 'Jl. Manyar Kertoarjo No. 15, Gubeng, Surabaya',
    originalPrice: 30000,
    discountPrice: 10000,
    price: 10000,
    quantity: '18 Porsi',
    pickupTime: '20:30 - 22:30 WIB',
    distance: '3.0 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Ayam Segar', 'Halal BPJPH', 'Wadah Food-Grade'],
    lat: -7.28,
    lng: 112.76,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-008',
    title: 'Pisang Cavendish Matang & Buah Segar',
    description: 'Buah pisang cavendish matang pohon higienis manis bernutrisi tinggi, cocok untuk nutrisi keluarga dan anak panti.',
    providerName: 'Superindo Fresh Mart',
    providerPhone: '081234567898',
    providerAddress: 'Jl. Raya Kertajaya Indah No. 5, Mulyorejo, Surabaya',
    originalPrice: 18000,
    discountPrice: 0,
    price: 0,
    quantity: '20 Sisir',
    pickupTime: '18:00 - 20:00 WIB',
    distance: '2.5 km',
    category: 'BUAH_SAYUR',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'BULK',
    weightPerUnitKg: 1.0,
    allergens: ['100% Organik', 'Tanpa Pestisida'],
    lat: -7.275,
    lng: 112.78,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-009',
    title: 'Nasi Rendang Daging Sapi Minang Asli',
    description: 'Paket nasi lauk rendang daging sapi empuk bumbu rempah kelapa asli Minang, dikemas dengan lalapan daun singkong steril.',
    providerName: 'Resto Padang Sederhana',
    providerPhone: '081299881122',
    providerAddress: 'Jl. Tebet Barat Dalam Raya No. 18, Tebet, Jakarta Selatan',
    originalPrice: 38000,
    discountPrice: 16000,
    price: 16000,
    quantity: '10 Porsi',
    pickupTime: '19:30 - 21:00 WIB',
    distance: '2.4 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.45,
    allergens: ['Daging Sapi Halal', 'Santan Segar', 'Halal BPJPH'],
    lat: -6.2361,
    lng: 106.8527,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-010',
    title: 'Aneka Artisan Sourdough & Baguette Perancis',
    description: 'Koleksi roti fermentasi alami sourdough dan baguette renyah dari tepung gandum utuh, higienis tanpa bahan pengawet.',
    providerName: 'Dago Bakery Heritage',
    providerPhone: '081277665544',
    providerAddress: 'Jl. Ir. H. Juanda No. 102, Dago, Bandung',
    originalPrice: 26000,
    discountPrice: 9000,
    price: 9000,
    quantity: '16 Paket',
    pickupTime: '20:00 - 21:30 WIB',
    distance: '2.6 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Gluten Gandum', 'Bebas Pengawet', 'Halal'],
    lat: -6.8856,
    lng: 107.6139,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-011',
    title: 'Paket Susu Pasteurisasi Segar & Yogurt Greek',
    description: 'Susu sapi pasteurisasi dingin berkualitas tinggi dan yogurt greek probiotik dalam kemasan botol segel utuh pabrik.',
    providerName: 'Greenfields Fresh Hub',
    providerPhone: '081399887711',
    providerAddress: 'Jl. Kaliurang Km 5, Depok, Sleman, Yogyakarta',
    originalPrice: 25000,
    discountPrice: 0,
    price: 0,
    quantity: '25 Botol',
    pickupTime: '18:30 - 20:00 WIB',
    distance: '1.8 km',
    category: 'MINUMAN_SUSU',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Susu Sapi Segar', 'Kalsium Alami', 'Halal BPJPH'],
    lat: -7.7554,
    lng: 110.3846,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-012',
    title: 'Paket Sayuran Hidroponik & Selada Romaine',
    description: 'Sayuran hijau selada romaine, pakcoy, dan bayam hidroponik bebas pestisida, dipanen sore hari dengan akar basah steril.',
    providerName: 'Kebun Hidroponik Lestari',
    providerPhone: '081266554433',
    providerAddress: 'Jl. Teuku Umar No. 50, Candisari, Semarang',
    originalPrice: 20000,
    discountPrice: 0,
    price: 0,
    quantity: '15 Pack',
    pickupTime: '18:00 - 19:30 WIB',
    distance: '2.1 km',
    category: 'BUAH_SAYUR',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.8,
    allergens: ['Bebas Pestisida', '100% Vegan & Halal'],
    lat: -7.0125,
    lng: 110.4289,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-013',
    title: 'Beras Premium Ramos Super Bersih 5kg',
    description: 'Beras putih pulen kualitas premium tanpa pewarna dan pemutih, aman dan bergizi tinggi untuk kebutuhan panti.',
    providerName: 'Lumbung Pangan Berkah',
    providerPhone: '081288992233',
    providerAddress: 'Jl. Padang Bulan No. 120, Medan Baru, Medan',
    originalPrice: 72000,
    discountPrice: 0,
    price: 0,
    quantity: '8 Sak',
    pickupTime: '16:00 - 18:30 WIB',
    distance: '3.0 km',
    category: 'BAHAN_MENTAH',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 5.0,
    allergens: ['Bebas Pengawet', 'Halal BPJPH', 'Mutu Dinsos'],
    lat: 3.5852,
    lng: 98.6756,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-014',
    title: 'Bento Chicken Katsu Rice Bowl',
    description: 'Fillet ayam katsu renyah dengan nasi jepang pulen, saus katsu gurih, dan coleslaw sayur segar terpisah.',
    providerName: 'Tokyo Bento & Katsu House',
    providerPhone: '081211223344',
    providerAddress: 'Jl. Senopati No. 44, Kebayoran Baru, Jakarta Selatan',
    originalPrice: 36000,
    discountPrice: 14000,
    price: 14000,
    quantity: '12 Porsi',
    pickupTime: '20:00 - 21:45 WIB',
    distance: '2.8 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Ayam Segar', 'Tepung Roti', 'Halal BPJPH'],
    lat: -6.2289,
    lng: 106.8083,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-015',
    title: 'Paket Bento Teriyaki Ayam & Salad Steril (Habis)',
    description: 'Bento daging ayam teriyaki gurih manis dengan salad kol segar dan nasi hangat. Seluruh porsi untuk slot hari ini telah habis diklaim.',
    providerName: 'HokBen Tunjungan Plaza Surabaya',
    providerPhone: '081234567895',
    providerAddress: 'Tunjungan Plaza 4 Lt. 5, Jl. Embong Malang, Surabaya',
    originalPrice: 38000,
    discountPrice: 15000,
    price: 15000,
    quantity: '0 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '0.9 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Ayam Teriyaki', 'Halal BPJPH'],
    lat: -7.2619,
    lng: 112.7396,
    status: 'OUT_OF_STOCK',
  },
  {
    id: 'FOD-016',
    title: 'Pisang Goreng Madu & Aneka Gorengan Higienis',
    description: 'Pisang raja goreng karamel madu alami dengan kulit renyah bebas minyak berlebih, dikemas dalam kotak berventilasi udara.',
    providerName: 'Dapur Pisang Madu Menteng',
    providerPhone: '081299887766',
    providerAddress: 'Jl. HOS Cokroaminoto No. 32, Menteng, Jakarta Pusat',
    originalPrice: 20000,
    discountPrice: 8000,
    price: 8000,
    quantity: '20 Porsi',
    pickupTime: '18:00 - 20:30 WIB',
    distance: '1.5 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Pisang Raja', 'Madu Murni', 'Halal BPJPH'],
    lat: -6.1963,
    lng: 106.8315,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-017',
    title: 'Soto Betawi Daging Sapi Kuah Susu Steril',
    description: 'Soto Betawi otentik potongan daging sapi empuk dengan kuah susu gurih rempah pala kapulaga, lengkap emping dan sambal.',
    providerName: 'Soto Betawi H. Husein Jakarta',
    providerPhone: '081388776655',
    providerAddress: 'Jl. Padang Panjang No. 8C, Manggarai, Jakarta Selatan',
    originalPrice: 42000,
    discountPrice: 18000,
    price: 18000,
    quantity: '18 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '2.4 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'STERILE_CONTAINER',
    weightPerUnitKg: 0.45,
    allergens: ['Daging Sapi Segar', 'Susu Steril', 'Halal BPJPH'],
    lat: -6.2114,
    lng: 106.8488,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-018',
    title: 'Bolen Pisang Keju Cokelat Halal',
    description: 'Pastry bolen khas Bandung dengan isian pisang lumer, keju kraft gurih, dan taburan meses cokelat premium.',
    providerName: 'Prima Rasa Bakery Bandung',
    providerPhone: '081222334455',
    providerAddress: 'Jl. Kemuning No. 20, Merdeka, Sumur Bandung, Kota Bandung',
    originalPrice: 45000,
    discountPrice: 20000,
    price: 20000,
    quantity: '25 Box',
    pickupTime: '19:30 - 21:30 WIB',
    distance: '1.1 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Dairy (Keju & Susu)', 'Gluten', 'Halal BPJPH'],
    lat: -6.9147,
    lng: 107.6098,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-019',
    title: 'Nasi Timbel Komplit Ayam Bakar Bumbu Parahyangan',
    description: 'Nasi timbel wangi bungkus daun pisang, ayam bakar rempah khas Priangan, tahu tempe goreng, dan lalapan timun segar.',
    providerName: 'Dapur Ampera Dago Bandung',
    providerPhone: '081333445566',
    providerAddress: 'Jl. Ir. H. Juanda No. 110, Dago, Coblong, Kota Bandung',
    originalPrice: 32000,
    discountPrice: 14000,
    price: 14000,
    quantity: '15 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '1.7 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.42,
    allergens: ['Ayam Segar', 'Kacang Kedelai (Tempe/Tahu)', 'Halal BPJPH'],
    lat: -6.8856,
    lng: 107.6139,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-020',
    title: 'Paket Donasi Bubur Ayam Komplit (Habis Terbagi)',
    description: 'Bubur beras kaldu ayam kampung dengan suwiran ayam, kacang kedelai goreng, dan cakwe steril. Seluruh alokasi donasi telah tersalurkan.',
    providerName: 'Bubur Ayam Mang Oyo Bandung',
    providerPhone: '081299334411',
    providerAddress: 'Jl. Gelap Nyawang No. 4, Lebak Siliwangi, Bandung',
    originalPrice: 20000,
    discountPrice: 0,
    price: 0,
    quantity: '0 Porsi',
    pickupTime: '18:30 - 20:00 WIB',
    distance: '2.0 km',
    category: 'MAKANAN_BERAT',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'STERILE_CONTAINER',
    weightPerUnitKg: 0.38,
    allergens: ['Ayam Kaldu', 'Halal BPJPH'],
    lat: -6.8924,
    lng: 107.6102,
    status: 'OUT_OF_STOCK',
  },
  {
    id: 'FOD-021',
    title: 'Gudeg Komplit Telur & Tahu Bacem Steril',
    description: 'Gudeg nangka muda manis gurih khas Jogja dengan telur bebek bacem, tahu bacem empuk, dan areh santan kental terpisah.',
    providerName: 'Gudeg Yu Djum Wijilan Yogyakarta',
    providerPhone: '081227889900',
    providerAddress: 'Jl. Wijilan No. 167, Panembahan, Kraton, Yogyakarta',
    originalPrice: 28000,
    discountPrice: 12000,
    price: 12000,
    quantity: '22 Porsi',
    pickupTime: '19:00 - 21:30 WIB',
    distance: '1.3 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Telur Bebek', 'Kedelai Tahu', 'Halal BPJPH'],
    lat: -7.8048,
    lng: 110.3683,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-022',
    title: 'Lumpia Basah & Goreng Rebung Halal',
    description: 'Lumpia khas Semarang dengan isian rebung manis gurih, telur orak-arik, dan saus kental bawang putih daun bawang segar.',
    providerName: 'Resto Lumpia Mataram Pandanaran',
    providerPhone: '081229988112',
    providerAddress: 'Jl. Pandanaran No. 73, Mugassari, Semarang Selatan',
    originalPrice: 18000,
    discountPrice: 8000,
    price: 8000,
    quantity: '30 Porsi',
    pickupTime: '18:30 - 21:00 WIB',
    distance: '1.6 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.3,
    allergens: ['Rebung Segar', 'Telur', 'Halal BPJPH'],
    lat: -6.9904,
    lng: 110.4184,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-023',
    title: 'Paket Salad Buah Segar Tropis & Yoghurt Probiotik',
    description: 'Potongan melon, semangka, pepaya, dan buah naga segar disajikan dengan saus yoghurt probiotik dan keju parut terpisah.',
    providerName: 'Bali Fresh Salad & Bowl Sunset Road',
    providerPhone: '081338877661',
    providerAddress: 'Jl. Sunset Road No. 88, Kuta, Badung, Bali',
    originalPrice: 25000,
    discountPrice: 10000,
    price: 10000,
    quantity: '16 Cup',
    pickupTime: '18:00 - 20:30 WITA',
    distance: '2.1 km',
    category: 'BUAH_SAYUR',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Susu Fermentasi (Yoghurt)', '100% Buah Segar Alami'],
    lat: -8.7032,
    lng: 115.1764,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-024',
    title: 'Nasi Kotak Ayam Betutu Khas Bali Rempah Steril',
    description: 'Ayam panggang oven rempah base genep Bali kaya kunyit jahe serai, sambal matah steril, dan kacang goreng renyah.',
    providerName: 'Ayam Betutu Khas Gilimanuk Kuta',
    providerPhone: '081236655441',
    providerAddress: 'Jl. Raya Kuta No. 43, Kuta, Badung, Bali',
    originalPrice: 38000,
    discountPrice: 16000,
    price: 16000,
    quantity: '20 Porsi',
    pickupTime: '19:30 - 21:30 WITA',
    distance: '1.9 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.44,
    allergens: ['Ayam Kampung', 'Kacang Tanah', 'Halal BPJPH'],
    lat: -8.7208,
    lng: 115.1729,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-025',
    title: 'Coto Daging Rempah Nusantara & Ketupat Daun',
    description: 'Kuah coto daging sapi kental rempah kacang sangrai khas Makassar, disajikan dengan potongan ketupat daun kelapa higienis.',
    providerName: 'Coto Nusantara Losari Makassar',
    providerPhone: '081244556677',
    providerAddress: 'Jl. Nusantara No. 32, Wajo, Kota Makassar, Sulawesi Selatan',
    originalPrice: 35000,
    discountPrice: 15000,
    price: 15000,
    quantity: '25 Porsi',
    pickupTime: '19:00 - 21:30 WITA',
    distance: '2.5 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'STERILE_CONTAINER',
    weightPerUnitKg: 0.42,
    allergens: ['Daging Sapi Segar', 'Kacang Sangrai Halus', 'Halal BPJPH'],
    lat: -5.1354,
    lng: 119.4082,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-026',
    title: 'Bolu Gulung Mocca & Keju Spesial Medan',
    description: 'Bolu gulung lembut dengan selai mocca wangi dan taburan keju cheddar melimpah, baru selesai dipanggang dan tersegel vakum.',
    providerName: 'Bolu Meranti Khas Medan',
    providerPhone: '081266778899',
    providerAddress: 'Jl. Kruing No. 2K, Sekip, Medan Petisah, Kota Medan',
    originalPrice: 65000,
    discountPrice: 28000,
    price: 28000,
    quantity: '14 Kotak',
    pickupTime: '18:30 - 21:00 WIB',
    distance: '2.2 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.6,
    allergens: ['Telur Segar', 'Keju Cheddar', 'Gluten', 'Halal BPJPH'],
    lat: 3.5931,
    lng: 98.6711,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-027',
    title: 'Apel Fuji Manis & Jeruk Medan Segar Supermarket',
    description: 'Koleksi buah apel fuji renyah manis dan jeruk medan berkadar vitamin C tinggi dari rak chilled supermarket, disortir segar setiap sore.',
    providerName: 'Superindo Fresh Mart Mulyosari',
    providerPhone: '081234567801',
    providerAddress: 'Jl. Raya Mulyosari No. 82, Mulyorejo, Surabaya',
    originalPrice: 28000,
    discountPrice: 11000,
    price: 11000,
    quantity: '18 Kantong',
    pickupTime: '19:00 - 21:30 WIB',
    distance: '2.1 km',
    category: 'BUAH_SAYUR',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 1.0,
    allergens: ['100% Buah Alami', 'Bebas Lilin Pengawet'],
    lat: -7.2655,
    lng: 112.7850,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-028',
    title: 'Daging Ayam Potong Segar Segel Pabrik Dingin (Halal)',
    description: 'Paket karkas daging ayam broiler segar bersertifikat Halal MUI dari counter fresh meat Hypermart, disimpan dalam cold storage 2°C berstandar BPOM.',
    providerName: 'Hypermart Food Savior Royal Plaza',
    providerPhone: '081234567802',
    providerAddress: 'Royal Plaza Lt. LG, Jl. Ahmad Yani No. 16-18, Wonokromo, Surabaya',
    originalPrice: 42000,
    discountPrice: 17000,
    price: 17000,
    quantity: '15 Pack',
    pickupTime: '20:00 - 22:00 WIB',
    distance: '2.8 km',
    category: 'BAHAN_MENTAH',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.9,
    allergens: ['Ayam Segar Higienis', 'Halal BPJPH', 'Chilled Chain'],
    lat: -7.3054,
    lng: 112.7341,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-029',
    title: 'Onigiri Salmon Mayo & Sandwich Gandum Siap Santap',
    description: 'Menu siap santap onigiri nasi jepang isi salmon mayo dan sandwich roti gandum lapis smoked beef telur, higienis dan tersegel kemasan kedap udara.',
    providerName: 'Indomaret Fresh Hub Gubeng Station',
    providerPhone: '081234567803',
    providerAddress: 'Jl. Gubeng Masjid No. 2, Tambaksari, Surabaya',
    originalPrice: 22000,
    discountPrice: 7500,
    price: 7500,
    quantity: '25 Pcs',
    pickupTime: '18:30 - 21:30 WIB',
    distance: '0.8 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.25,
    allergens: ['Ikan Salmon', 'Telur', 'Gluten', 'Halal BPJPH'],
    lat: -7.2654,
    lng: 112.7512,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-030',
    title: 'Roti Gandum Supermarket & Butter Croissant Prancis',
    description: 'Roti tawar gandum whole wheat kaya serat dan butter croissant renyah dari in-store bakery Hero Supermarket, dipanggang pagi hari tanpa bahan kimia.',
    providerName: 'Hero Supermarket Grand City Surabaya',
    providerPhone: '081234567804',
    providerAddress: 'Grand City Mall Lt. B, Jl. Walikota Mustajab No. 1, Genteng, Surabaya',
    originalPrice: 35000,
    discountPrice: 12000,
    price: 12000,
    quantity: '20 Bungkus',
    pickupTime: '19:30 - 21:45 WIB',
    distance: '1.2 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.45,
    allergens: ['Gluten Gandum', 'Dairy (Susu & Mentega)', 'Halal'],
    lat: -7.2608,
    lng: 112.7481,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-031',
    title: 'Susu Segar Murni Pasteurisasi Sapi Malang (Chilled 2-4°C)',
    description: 'Susu sapi murni pasteurisasi segar hasil perahan pagi hari peternak Pujon Malang, terjaga rantai dingin chilled 2-4°C, kaya kalsium alami dan bebas pengawet.',
    providerName: 'Koperasi Susu Perah Pujon Malang',
    providerPhone: '081234567831',
    providerAddress: 'Depo Susu Segar Surabaya, Jl. Raya Darmo No. 48, Tegalsari, Surabaya',
    originalPrice: 22000,
    discountPrice: 7000,
    price: 7000,
    quantity: '20 Botol (1 Liter)',
    pickupTime: '17:00 - 20:30 WIB',
    distance: '1.4 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 1.0,
    allergens: ['Laktosa (Susu Sapi Murni)', 'Halal BPJPH', 'Chilled 2-4°C (BPOM RI)'],
    lat: -7.2798,
    lng: 112.7381,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-032',
    title: 'Susu Oat Barista & Susu Kedelai Organik (Lactose-Free)',
    description: 'Susu nabati oat milk barista blend dan kedelai organik non-GMO kaya serat, bebas laktosa (lactose-free), cocok untuk vegan dan intoleransi susu sapi.',
    providerName: 'Artisan Coffee & Plant Milk Roastery',
    providerPhone: '081234567832',
    providerAddress: 'Jl. Kayoon No. 22, Embong Kaliasin, Genteng, Surabaya',
    originalPrice: 28000,
    discountPrice: 9000,
    price: 9000,
    quantity: '18 Botol (750ml)',
    pickupTime: '18:00 - 21:00 WIB',
    distance: '1.1 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.75,
    allergens: ['100% Plant-Based (Vegan)', 'Bebas Laktosa', 'Halal BPJPH'],
    lat: -7.2685,
    lng: 112.7489,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-033',
    title: 'Jus Buah Cold-Pressed Jeruk Murni & Apel Hijau 100%',
    description: 'Jus buah cold-pressed 100% murni tanpa tambahan air dan tanpa pemanis buatan, diekstrak secara hidrolik dingin kaya enzim aktif dan vitamin C.',
    providerName: 'Fresh Juice Bar Galaxy Mall',
    providerPhone: '081234567833',
    providerAddress: 'Galaxy Mall 3 Lt. 2, Jl. Dharmahusada Indah Timur, Mulyorejo, Surabaya',
    originalPrice: 25000,
    discountPrice: 8500,
    price: 8500,
    quantity: '25 Botol (350ml)',
    pickupTime: '19:00 - 21:30 WIB',
    distance: '2.0 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['100% Buah Murni', 'Tanpa Gula Tambahan', 'Chilled 4°C'],
    lat: -7.2755,
    lng: 112.7812,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-034',
    title: 'Paket Karton Susu UHT Steril Full Cream (Donasi Panti)',
    description: 'Paket susu UHT kotak steril kemasan tetra pak higienis kaya vitamin D dan kalsium, dialokasikan gratis Rp 0 untuk asupan gizi anak-anak panti asuhan binaan.',
    providerName: 'Gudang Distribusi Pangan Berkah',
    providerPhone: '081234567834',
    providerAddress: 'Kawasan Industri Rungkut Megah No. 18, Rungkut, Surabaya',
    originalPrice: 65000,
    discountPrice: 0,
    price: 0,
    quantity: '30 Karton (24x200ml)',
    pickupTime: '16:00 - 19:30 WIB',
    distance: '2.7 km',
    category: 'MINUMAN_SUSU',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 5.2,
    allergens: ['Susu Sapi Steril UHT', 'Halal MUI / BPJPH', 'SNI 01-3950'],
    lat: -7.3245,
    lng: 112.7612,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-035',
    title: 'Specialty Cold Brew Coffee & Uji Matcha Latte Botol Kaca',
    description: 'Kopi cold brew seduh dingin 16 jam biji Arabika Ijen dan matcha latte susu segar dalam botol kaca higienis bersegel aluminium.',
    providerName: 'Titik Koma Coffee & Bakery Surabaya',
    providerPhone: '081234567835',
    providerAddress: 'Jl. Juwono No. 2, Darmo, Wonokromo, Surabaya',
    originalPrice: 32000,
    discountPrice: 10000,
    price: 10000,
    quantity: '22 Botol (250ml)',
    pickupTime: '19:30 - 22:00 WIB',
    distance: '0.9 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.3,
    allergens: ['Kafein Alami', 'Susu Segar Pasteurisasi', 'Halal BPJPH'],
    lat: -7.2891,
    lng: 112.7412,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-036',
    title: 'Yogurt Drink Probiotik Stroberi & Mixed Berries',
    description: 'Minuman yogurt fermentasi kultur bakteri probiotik hidup (Lactobacillus) dengan bulir buah stroberi asli untuk kesehatan sistem pencernaan.',
    providerName: 'Cimory Dairy Corner Darmo',
    providerPhone: '081234567836',
    providerAddress: 'Jl. Raya Darmo No. 112, Wonokromo, Surabaya',
    originalPrice: 19000,
    discountPrice: 6500,
    price: 6500,
    quantity: '25 Pcs (300ml)',
    pickupTime: '18:00 - 21:00 WIB',
    distance: '1.6 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.32,
    allergens: ['Susu Fermentasi Probiotik', 'Buah Asli', 'Halal BPJPH'],
    lat: -7.2945,
    lng: 112.7390,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-037',
    title: 'Susu Kurma Almond Sehat & Madu Habbatus Sauda (Donasi)',
    description: 'Minuman nutrisi perpaduan kurma sukari pilihan, susu almond nabati, dan madu murni, bebas gula tebu, donasi gratis untuk lansia & panti dhuafa.',
    providerName: 'Katering Sehat Nabawi Surabaya',
    providerPhone: '081234567837',
    providerAddress: 'Jl. Semampir Barat No. 14, Ampel, Semampir, Surabaya',
    originalPrice: 28000,
    discountPrice: 0,
    price: 0,
    quantity: '20 Botol (330ml)',
    pickupTime: '17:00 - 19:30 WIB',
    distance: '2.2 km',
    category: 'MINUMAN_SUSU',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Kacang Almond', 'Kurma Alami', '100% Halal Alami'],
    lat: -7.2285,
    lng: 112.7482,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-038',
    title: 'Artisan Iced Lemon Tea & Teh Melati Seduh Segar',
    description: 'Teh melati wangi dan teh lemon mint segar diseduh dari daun teh pucuk peko pilihan, dikemas dalam cup sealed anti bocor.',
    providerName: 'Dapoer Daun Pandan & Kopi',
    providerPhone: '081234567838',
    providerAddress: 'Jl. Walikota Mustajab No. 28, Genteng, Surabaya',
    originalPrice: 15000,
    discountPrice: 4000,
    price: 4000,
    quantity: '30 Cup (500ml)',
    pickupTime: '18:30 - 21:30 WIB',
    distance: '0.7 km',
    category: 'MINUMAN_SUSU',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Teh Alami', 'Ekstrak Lemon Segar', 'Halal BPJPH'],
    lat: -7.2625,
    lng: 112.7455,
    status: 'AVAILABLE',
  },
];

// Comprehensive Database of Demo Accounts across Indonesia
export interface DemoAccount {
  email: string;
  phone: string;
  name: string;
  role: 'FOOD_PROVIDER' | 'FOOD_BENEFICIARY' | 'FOOD_CONSUMER' | 'RESCUE_VOLUNTEER' | 'SUPER_ADMIN';
  entityName: string;
  contactPerson: string;
  city: string;
  address: string;
  description: string;
}

export const DEMO_ACCOUNTS_DATABASE: DemoAccount[] = [
  // 1. Food Consumers
  {
    email: 'budi.santoso@gmail.com',
    phone: '0813-4567-8901',
    name: 'Budi Santoso',
    role: 'FOOD_CONSUMER',
    entityName: 'Budi Santoso',
    contactPerson: 'Budi Santoso',
    city: 'Surabaya',
    address: 'Jl. Ketintang No. 12, Gayungan, Surabaya',
    description: 'Konsumen Mahasiswa Reguler (Surabaya)',
  },
  {
    email: 'sarah.amelia@gmail.com',
    phone: '0812-9876-5431',
    name: 'Sarah Amelia',
    role: 'FOOD_CONSUMER',
    entityName: 'Sarah Amelia',
    contactPerson: 'Sarah Amelia',
    city: 'Jakarta',
    address: 'Jl. Tebet Barat Dalam No. 45, Tebet, Jakarta Selatan',
    description: 'Konsumen Karyawan Swasta (Jakarta)',
  },
  {
    email: 'rizki.pratama@gmail.com',
    phone: '0812-3344-5566',
    name: 'Rizki Pratama',
    role: 'FOOD_CONSUMER',
    entityName: 'Rizki Pratama',
    contactPerson: 'Rizki Pratama',
    city: 'Bandung',
    address: 'Jl. Dipatiukur No. 88, Coblong, Kota Bandung',
    description: 'Konsumen Mahasiswa Unpad (Bandung)',
  },
  {
    email: 'dewi.lestari@gmail.com',
    phone: '0813-7788-9900',
    name: 'Dewi Lestari',
    role: 'FOOD_CONSUMER',
    entityName: 'Dewi Lestari',
    contactPerson: 'Dewi Lestari',
    city: 'Yogyakarta',
    address: 'Jl. Kaliurang KM 5, Sleman, DI Yogyakarta',
    description: 'Konsumen Umum Peduli Lingkungan (Yogyakarta)',
  },

  // 2. Food Providers
  {
    email: 'bakso.pak.kumis@replate.id',
    phone: '0812-3456-7891',
    name: 'Warung Bakso Pak Kumis',
    role: 'FOOD_PROVIDER',
    entityName: 'Warung Bakso Pak Kumis',
    contactPerson: 'Pak Doni (Kepala Gerai)',
    city: 'Surabaya',
    address: 'Jl. Genteng Kali No. 45, Genteng, Surabaya',
    description: 'Restoran Kuliner Bakso & Mie Ayam Halal (Surabaya)',
  },
  {
    email: 'rotiboy.tunjungan@replate.id',
    phone: '0812-3456-7892',
    name: 'Rotiboy Bakery Tunjungan Plaza',
    role: 'FOOD_PROVIDER',
    entityName: 'Rotiboy Bakery Tunjungan Plaza',
    contactPerson: 'Mbak Rina (Supervisor Kasir)',
    city: 'Surabaya',
    address: 'Tunjungan Plaza Lt. G, Jl. Basuki Rahmat, Surabaya',
    description: 'Bakery & Pastry Harian Steril (Surabaya)',
  },
  {
    email: 'hotel.majapahit@replate.id',
    phone: '0812-3456-7893',
    name: 'Hotel Majapahit Surabaya MGallery',
    role: 'FOOD_PROVIDER',
    entityName: 'Hotel Majapahit Surabaya',
    contactPerson: 'Executive Chef Hendra',
    city: 'Surabaya',
    address: 'Jl. Tunjungan No. 65, Genteng, Surabaya',
    description: 'Hotel Bintang 5 Penyedia Buffet Surplus (Surabaya)',
  },
  {
    email: 'dapur.berkah.menteng@replate.id',
    phone: '0812-9988-7766',
    name: 'Dapur Katering Berkah Menteng',
    role: 'FOOD_PROVIDER',
    entityName: 'Dapur Katering Berkah Menteng',
    contactPerson: 'Ibu Hj. Sulastri',
    city: 'Jakarta',
    address: 'Jl. HOS Cokroaminoto No. 32, Menteng, Jakarta Pusat',
    description: 'Katering Makanan Tradisional Nusantara (Jakarta)',
  },
  {
    email: 'primarasa.bandung@replate.id',
    phone: '0812-2233-4455',
    name: 'Prima Rasa Bakery Bandung',
    role: 'FOOD_PROVIDER',
    entityName: 'Prima Rasa Bakery Bandung',
    contactPerson: 'Pak Hendra Gunawan',
    city: 'Bandung',
    address: 'Jl. Kemuning No. 20, Merdeka, Sumur Bandung, Bandung',
    description: 'Bakery & Pastry Khas Bandung (Bandung)',
  },

  // 3. Food Beneficiaries (Panti Asuhan & Yayasan)
  {
    email: 'panti.kasih.ibu@replate.id',
    phone: '0812-3456-7890',
    name: 'Panti Asuhan Kasih Ibu Surabaya',
    role: 'FOOD_BENEFICIARY',
    entityName: 'Panti Asuhan Kasih Ibu Surabaya',
    contactPerson: 'Ibu Hajjah Maryam (Ketua Pengurus)',
    city: 'Surabaya',
    address: 'Jl. Raya Gubeng No. 88, Gubeng, Surabaya',
    description: 'Panti Asuhan 80 Anak Asuh & Dhuafa (Surabaya)',
  },
  {
    email: 'sayap.ibu.jakarta@replate.id',
    phone: '0813-8899-7711',
    name: 'Yayasan Sayap Ibu Cabang Jakarta',
    role: 'FOOD_BENEFICIARY',
    entityName: 'Yayasan Sayap Ibu Jakarta',
    contactPerson: 'Dra. Ratna Handayani',
    city: 'Jakarta',
    address: 'Jl. Barito II No. 55, Kebayoran Baru, Jakarta Selatan',
    description: 'Panti Asuhan Bayi & Balita Terlantar (Jakarta)',
  },
  {
    email: 'kasih.anak.kanker@replate.id',
    phone: '0812-7766-5544',
    name: 'Yayasan Kasih Anak Kanker Bandung',
    role: 'FOOD_BENEFICIARY',
    entityName: 'Yayasan Kasih Anak Kanker Bandung',
    contactPerson: 'Ibu Dr. Maya Safitri',
    city: 'Bandung',
    address: 'Jl. Cihampelas No. 142, Coblong, Kota Bandung',
    description: 'Rumah Singgah Nutrisi Pasien Anak Kanker (Bandung)',
  },
  {
    email: 'panti.diponegoro.jogja@replate.id',
    phone: '0813-2211-9988',
    name: 'Panti Asuhan Pangeran Diponegoro Yogyakarta',
    role: 'FOOD_BENEFICIARY',
    entityName: 'Panti Asuhan Pangeran Diponegoro Yogyakarta',
    contactPerson: 'Ustadz Ahmad Fauzi, S.Pd.I',
    city: 'Yogyakarta',
    address: 'Jl. Ring Road Utara No. 20, Sleman, DI Yogyakarta',
    description: 'Pondok Asuh Dhuafa & Yatim Berprestasi (Yogyakarta)',
  },
  {
    email: 'panti.washliyah.medan@replate.id',
    phone: '0812-6655-4422',
    name: 'Panti Asuhan Al-Jamiyatul Washliyah Medan',
    role: 'FOOD_BENEFICIARY',
    entityName: 'Panti Asuhan Al-Jamiyatul Washliyah Medan',
    contactPerson: 'H. Rusli Siregar',
    city: 'Medan',
    address: 'Jl. Ismailiyah No. 82, Matsum, Kota Medan',
    description: 'Pusat Pembinaan 120 Santri Panti (Medan)',
  },

  // 4. Food Rescue Volunteers (Armada Relawan Logistik)
  {
    email: 'foodbank.surabaya@replate.id',
    phone: '0819-8765-4321',
    name: 'Komunitas Foodbank Surabaya Center',
    role: 'RESCUE_VOLUNTEER',
    entityName: 'Komunitas Foodbank Surabaya Center',
    contactPerson: 'Mas Rizky Multazam',
    city: 'Surabaya',
    address: 'Posko Logistik Relawan, Jl. Pemuda No. 45, Genteng, Surabaya',
    description: 'Armada Motor Box Cooler Steril Rute Surabaya Raya',
  },
  {
    email: 'foodrescue.jakarta@replate.id',
    phone: '0818-1234-5678',
    name: 'Jakarta Food Rescue Network',
    role: 'RESCUE_VOLUNTEER',
    entityName: 'Jakarta Food Rescue Network',
    contactPerson: 'Dimas Wicaksono',
    city: 'Jakarta',
    address: 'Posko Logistik Senopati, Kebayoran Baru, Jakarta Selatan',
    description: 'Armada Mobil Van Rantai Dingin DKI Jakarta',
  },
  {
    email: 'relawan.pangan.pasundan@replate.id',
    phone: '0819-2233-4455',
    name: 'Relawan Penyelamat Pangan Pasundan',
    role: 'RESCUE_VOLUNTEER',
    entityName: 'Relawan Penyelamat Pangan Pasundan',
    contactPerson: 'Kang Asep Kurniawan',
    city: 'Bandung',
    address: 'Jl. Riau No. 80, Cihapit, Bandung Wetan, Bandung',
    description: 'Komunitas Relawan Logistik Pangan Bandung Raya',
  },

  // 5. SuperAdmin / Pengawas BPOM
  {
    email: 'admin@replate.id',
    phone: '0812-3456-7890',
    name: 'SuperAdmin Pengawas Replate & Auditor BPOM',
    role: 'SUPER_ADMIN',
    entityName: 'Tim Auditor Keamanan Pangan Replate',
    contactPerson: 'Dr. Ir. Bambang Suhartono, M.Sc (BPOM Specialist)',
    city: 'Surabaya',
    address: 'Gedung Pemkot Surabaya & Balai Besar POM',
    description: 'SuperAdmin Tim Verifikasi NIB, Audit Sertifikasi, & BPOM RI',
  },
];

// Helper to check if an email or phone belongs to the Demo Database
export function isDemoAccount(email?: string | null, phone?: string | null): boolean {
  if (!email && !phone) return false;
  const cleanEmail = (email || '').trim().toLowerCase();
  const cleanPhone = (phone || '').replace(/\D/g, '');

  return DEMO_ACCOUNTS_DATABASE.some((acc) => {
    const accEmail = acc.email.trim().toLowerCase();
    const accPhone = acc.phone.replace(/\D/g, '');
    return (cleanEmail && accEmail === cleanEmail) || (cleanPhone && accPhone === cleanPhone);
  });
}

export function getAllDemoEmails(): string[] {
  return DEMO_ACCOUNTS_DATABASE.map((a) => a.email.toLowerCase());
}

export function getAllDemoPhones(): string[] {
  return DEMO_ACCOUNTS_DATABASE.map((a) => a.phone.replace(/\D/g, ''));
}

// Helper deduplication for panti needs
export function deduplicatePantiNeeds<T extends { id?: string; pantiName?: string; needTitle?: string; imageUrl?: string }>(items: T[]): T[] {
  if (!Array.isArray(items)) return [];
  const seenIds = new Set<string>();
  const seenNames = new Set<string>();

  return items.filter((item) => {
    if (!item) return false;
    const idKey = item.id ? String(item.id).trim().toLowerCase() : null;
    
    // Normalize name by removing generic prefixes and non-alphanumeric chars
    const rawName = (item.pantiName || '').trim().toLowerCase();
    const cleanName = rawName.replace(/panti\s*asuhan|yayasan|rumah\s*singgah|shelter/gi, '').replace(/[^a-z0-9]/g, '');
    const nameKey = cleanName.length > 2 ? cleanName : rawName.replace(/[^a-z0-9]/g, '');

    if (idKey && seenIds.has(idKey)) return false;
    if (nameKey && seenNames.has(nameKey)) return false;

    if (idKey) seenIds.add(idKey);
    if (nameKey) seenNames.add(nameKey);
    return true;
  });
}
