// Centralized Mock Database for Replate / FoodBridge
// Single Source of Truth for surplus foods across Explore, Dashboard Explore, and Dashboard Consumer

export interface MockFoodItem {
  id: string;
  title: string;
  description: string;
  providerName: string;
  providerPhone: string;
  providerAddress: string;
  originalPrice: number;
  discountPrice: number;
  price: number;
  quantity: string;
  pickupTime: string;
  distance: string;
  category: 'MAKANAN_BERAT' | 'ROTI_KUE' | 'MINUMAN_SUSU' | 'BUAH_SAYUR' | 'BAHAN_MENTAH';
  isFree: boolean;
  type: 'RESCUE_SALE' | 'DONATION';
  imageUrl: string;
  rating: number;
  storageCondition: 'ROOM_TEMP' | 'HOT_HOLDING' | 'CHILLED';
  packagingType: 'PACKAGED' | 'STERILE_CONTAINER' | 'BULK';
  weightPerUnitKg: number;
  allergens: string[];
  lat: number;
  lng: number;
  status: 'AVAILABLE' | 'CLAIMED' | 'EXPIRED';
}

export const MOCK_SURPLUS_FOODS: MockFoodItem[] = [
  {
    id: 'FOD-001',
    title: 'Nasi Paket Ayam Bakar Madu',
    description: 'Nasi hangat dengan ayam bakar madu bumbu rempah, lalapan segar, dan sambal terasi terpisah dalam wadah higienis berstandar BPOM.',
    providerName: 'Warung Bakso Pak Kumis',
    providerPhone: '081234567891',
    providerAddress: 'Jl. Genteng Kali No. 45, Genteng, Surabaya',
    originalPrice: 28000,
    discountPrice: 12000,
    price: 12000,
    quantity: '15 Porsi',
    pickupTime: '19:30 - 21:30 WIB',
    distance: '0.8 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Wadah Steril Food Grade'],
    lat: -7.2575,
    lng: 112.7521,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-002',
    title: 'Roti Croissant & Choco Pastry Halal',
    description: 'Aneka roti croissant butter dan pastry cokelat lembut yang baru dipanggang hari ini di outlet bakery, tersegel steril.',
    providerName: 'Rotiboy Bakery Surabaya',
    providerPhone: '081234567892',
    providerAddress: 'Tunjungan Plaza Lt. G, Jl. Basuki Rahmat, Surabaya',
    originalPrice: 18000,
    discountPrice: 6000,
    price: 6000,
    quantity: '25 Porsi',
    pickupTime: '20:00 - 22:00 WIB',
    distance: '1.2 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.25,
    allergens: ['Dairy (Susu)', 'Halal BPJPH', 'Bebas Pengawet'],
    lat: -7.2614,
    lng: 112.7385,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-003',
    title: 'Prasmanan Nasi Goreng & Ayam Goreng Buffet',
    description: 'Menu buffet katering hotel bintang 5 yang tidak tersentuh tamu, disimpan di warm chafing dish dengan suhu terjaga >60°C.',
    providerName: 'Hotel Majapahit Surabaya',
    providerPhone: '081234567893',
    providerAddress: 'Jl. Tunjungan No. 65, Surabaya',
    originalPrice: 45000,
    discountPrice: 0,
    price: 0,
    quantity: '30 Porsi',
    pickupTime: '20:30 - 22:00 WIB',
    distance: '2.1 km',
    category: 'MAKANAN_BERAT',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'STERILE_CONTAINER',
    weightPerUnitKg: 0.45,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Steril Food Grade'],
    lat: -7.2637,
    lng: 112.7407,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-004',
    title: 'Sop Buntut Sapi Kuah Rempah Steril',
    description: 'Sop buntut daging sapi dengan kuah kaldu rempah kaya gizi, dikemas dalam mangkok microwaveable kedap udara.',
    providerName: 'Dapur Katering Bu Rudy',
    providerPhone: '081234567894',
    providerAddress: 'Jl. Dharmahusada No. 140, Gubeng, Surabaya',
    originalPrice: 35000,
    discountPrice: 15000,
    price: 15000,
    quantity: '12 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '1.5 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Nut-Free', 'Halal BPJPH', 'Bebas MSG Berlebih'],
    lat: -7.2689,
    lng: 112.7681,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-005',
    title: 'Paket Roti Tawar Gandum & Donat Susu',
    description: 'Paket roti gandum tinggi serat dan donat tabur gula halus, higienis untuk sarapan atau camilan anak panti asuhan.',
    providerName: 'Bakery Plaza Surabaya',
    providerPhone: '081234567895',
    providerAddress: 'Jl. Pemuda No. 33, Surabaya Pusat',
    originalPrice: 22000,
    discountPrice: 0,
    price: 0,
    quantity: '20 Porsi',
    pickupTime: '20:30 - 21:45 WIB',
    distance: '1.8 km',
    category: 'ROTI_KUE',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.3,
    allergens: ['Dairy (Susu)', 'Halal BPJPH'],
    lat: -7.2655,
    lng: 112.7472,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-006',
    title: 'Sayur Sop Ayam Kaldu Organik (Porsi Jumbo)',
    description: 'Sup sayur kaldu ayam kaya nutrisi dengan wortel, kubis, brokoli segar steril dimasak higienis.',
    providerName: 'Dapur Sehat Bunda',
    providerPhone: '081234567896',
    providerAddress: 'Jl. Raya Darmo No. 12, Wonokromo, Surabaya',
    originalPrice: 22000,
    discountPrice: 8000,
    price: 8000,
    quantity: '14 Porsi',
    pickupTime: '19:00 - 21:00 WIB',
    distance: '2.1 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Bebas Pengawet', 'Rendah Garam', 'Halal'],
    lat: -7.265,
    lng: 112.75,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-007',
    title: 'Paket Dimsum Ayam & Siomay Kukus',
    description: 'Siomay dimsum ayam segar buatan pagi hari di restoran dimsum, steril dan lengkap dengan saus sambal sachet.',
    providerName: 'Dimsum Delight Nusantara',
    providerPhone: '081234567897',
    providerAddress: 'Jl. Manyar Kertoarjo No. 15, Gubeng, Surabaya',
    originalPrice: 30000,
    discountPrice: 10000,
    price: 10000,
    quantity: '18 Porsi',
    pickupTime: '20:30 - 22:30 WIB',
    distance: '3.0 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Ayam Segar', 'Halal BPJPH', 'Wadah Food-Grade'],
    lat: -7.28,
    lng: 112.76,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-008',
    title: 'Pisang Cavendish Matang & Buah Segar',
    description: 'Buah pisang cavendish matang pohon higienis manis bernutrisi tinggi, cocok untuk nutrisi keluarga dan anak panti.',
    providerName: 'Superindo Fresh Mart',
    providerPhone: '081234567898',
    providerAddress: 'Jl. Raya Kertajaya Indah No. 5, Mulyorejo, Surabaya',
    originalPrice: 18000,
    discountPrice: 0,
    price: 0,
    quantity: '20 Sisir',
    pickupTime: '18:00 - 20:00 WIB',
    distance: '2.5 km',
    category: 'BUAH_SAYUR',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'BULK',
    weightPerUnitKg: 1.0,
    allergens: ['100% Organik', 'Tanpa Pestisida'],
    lat: -7.275,
    lng: 112.78,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-009',
    title: 'Nasi Rendang Daging Sapi Minang Asli',
    description: 'Paket nasi lauk rendang daging sapi empuk bumbu rempah kelapa asli Minang, dikemas dengan lalapan daun singkong steril.',
    providerName: 'Resto Padang Sederhana',
    providerPhone: '081299881122',
    providerAddress: 'Jl. Tebet Barat Dalam Raya No. 18, Tebet, Jakarta Selatan',
    originalPrice: 38000,
    discountPrice: 16000,
    price: 16000,
    quantity: '10 Porsi',
    pickupTime: '19:30 - 21:00 WIB',
    distance: '2.4 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.45,
    allergens: ['Daging Sapi Halal', 'Santan Segar', 'Halal BPJPH'],
    lat: -6.2361,
    lng: 106.8527,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-010',
    title: 'Aneka Artisan Sourdough & Baguette Perancis',
    description: 'Koleksi roti fermentasi alami sourdough dan baguette renyah dari tepung gandum utuh, higienis tanpa bahan pengawet.',
    providerName: 'Dago Bakery Heritage',
    providerPhone: '081277665544',
    providerAddress: 'Jl. Ir. H. Juanda No. 102, Dago, Bandung',
    originalPrice: 26000,
    discountPrice: 9000,
    price: 9000,
    quantity: '16 Paket',
    pickupTime: '20:00 - 21:30 WIB',
    distance: '2.6 km',
    category: 'ROTI_KUE',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.35,
    allergens: ['Gluten Gandum', 'Bebas Pengawet', 'Halal'],
    lat: -6.8856,
    lng: 107.6139,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-011',
    title: 'Paket Susu Pasteurisasi Segar & Yogurt Greek',
    description: 'Susu sapi pasteurisasi dingin berkualitas tinggi dan yogurt greek probiotik dalam kemasan botol segel utuh pabrik.',
    providerName: 'Greenfields Fresh Hub',
    providerPhone: '081399887711',
    providerAddress: 'Jl. Kaliurang Km 5, Depok, Sleman, Yogyakarta',
    originalPrice: 25000,
    discountPrice: 0,
    price: 0,
    quantity: '25 Botol',
    pickupTime: '18:30 - 20:00 WIB',
    distance: '1.8 km',
    category: 'MINUMAN_SUSU',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.5,
    allergens: ['Susu Sapi Segar', 'Kalsium Alami', 'Halal BPJPH'],
    lat: -7.7554,
    lng: 110.3846,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-012',
    title: 'Paket Sayuran Hidroponik & Selada Romaine',
    description: 'Sayuran hijau selada romaine, pakcoy, dan bayam hidroponik bebas pestisida, dipanen sore hari dengan akar basah steril.',
    providerName: 'Kebun Hidroponik Lestari',
    providerPhone: '081266554433',
    providerAddress: 'Jl. Teuku Umar No. 50, Candisari, Semarang',
    originalPrice: 20000,
    discountPrice: 0,
    price: 0,
    quantity: '15 Pack',
    pickupTime: '18:00 - 19:30 WIB',
    distance: '2.1 km',
    category: 'BUAH_SAYUR',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    storageCondition: 'CHILLED',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.8,
    allergens: ['Bebas Pestisida', '100% Vegan & Halal'],
    lat: -7.0125,
    lng: 110.4289,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-013',
    title: 'Beras Premium Ramos Super Bersih 5kg',
    description: 'Beras putih pulen kualitas premium tanpa pewarna dan pemutih, aman dan bergizi tinggi untuk kebutuhan panti.',
    providerName: 'Lumbung Pangan Berkah',
    providerPhone: '081288992233',
    providerAddress: 'Jl. Padang Bulan No. 120, Medan Baru, Medan',
    originalPrice: 72000,
    discountPrice: 0,
    price: 0,
    quantity: '8 Sak',
    pickupTime: '16:00 - 18:30 WIB',
    distance: '3.0 km',
    category: 'BAHAN_MENTAH',
    isFree: true,
    type: 'DONATION',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=60',
    rating: 5.0,
    storageCondition: 'ROOM_TEMP',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 5.0,
    allergens: ['Bebas Pengawet', 'Halal BPJPH', 'Mutu Dinsos'],
    lat: 3.5852,
    lng: 98.6756,
    status: 'AVAILABLE',
  },
  {
    id: 'FOD-014',
    title: 'Bento Chicken Katsu Rice Bowl',
    description: 'Fillet ayam katsu renyah dengan nasi jepang pulen, saus katsu gurih, dan coleslaw sayur segar terpisah.',
    providerName: 'Tokyo Bento & Katsu House',
    providerPhone: '081211223344',
    providerAddress: 'Jl. Senopati No. 44, Kebayoran Baru, Jakarta Selatan',
    originalPrice: 36000,
    discountPrice: 14000,
    price: 14000,
    quantity: '12 Porsi',
    pickupTime: '20:00 - 21:45 WIB',
    distance: '2.8 km',
    category: 'MAKANAN_BERAT',
    isFree: false,
    type: 'RESCUE_SALE',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    storageCondition: 'HOT_HOLDING',
    packagingType: 'PACKAGED',
    weightPerUnitKg: 0.4,
    allergens: ['Ayam Segar', 'Tepung Roti', 'Halal BPJPH'],
    lat: -6.2289,
    lng: 106.8083,
    status: 'AVAILABLE',
  },
];

// Helper deduplication for panti needs
export function deduplicatePantiNeeds<T extends { id?: string; pantiName?: string; needTitle?: string; imageUrl?: string }>(items: T[]): T[] {
  if (!Array.isArray(items)) return [];
  const seenIds = new Set<string>();
  const seenNames = new Set<string>();

  return items.filter((item) => {
    if (!item) return false;
    const idKey = item.id ? String(item.id).trim().toLowerCase() : null;
    
    // Normalize name by removing generic prefixes and non-alphanumeric chars
    const rawName = (item.pantiName || '').trim().toLowerCase();
    const cleanName = rawName.replace(/panti\s*asuhan|yayasan|rumah\s*singgah|shelter/gi, '').replace(/[^a-z0-9]/g, '');
    const nameKey = cleanName.length > 2 ? cleanName : rawName.replace(/[^a-z0-9]/g, '');

    if (idKey && seenIds.has(idKey)) return false;
    if (nameKey && seenNames.has(nameKey)) return false;

    if (idKey) seenIds.add(idKey);
    if (nameKey) seenNames.add(nameKey);
    return true;
  });
}
